CitySushi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from CitySushi import views

urlpatterns = [
    path('orders/', include('orders.urls')),
    path('', views.index, name='home'),  # new
    path('accounts/', include('django.contrib.auth.urls')),  # new
    path('admin/', admin.site.urls),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.menu, name='menu'),
    path('main/', views.main, name='main'),
    path('orderplaced/', views.orderPlaced, name='orderplaced'),
    path('register/', views.customerRegister, name='register'),
    # For actual customers in model
    path('cregister/', views.realCustomerRegister, name='cregister'),
    path('cregister/', views.realCustomerRegister, name='cregister'),
    path('profile/', views.customerProfile, name='profile'),
    path('cooking/', views.cookView, name='cooking'),
    path('profile/addpayment', views.add_payment_form, name='addpayment'),
    path('customer/create/', views.createCustomer, name='ccreate'),
    path('review/<int:id>/', views.review, name='review'),
    path('user/update/<int:id>/', views.updateCustomer, name='cupdate'),
    # path('checkout/', views.checkout, name='checkout')
]

orders/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import Visitor, Customer, Review, PaymentInfo


class CustomerSignUpForm(forms.Form):
    username = forms.CharField(label='Username', min_length=5, max_length=20)
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Re-enter password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError("Email already exists")
        return email

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise ValidationError("Passwords don't match")

        return password_confirm

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password']
        )
        return user


class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Username', min_length=5, max_length=20)
    address = forms.CharField(label="Address", max_length=1024)
    zip_code = forms.CharField(label="ZIP / Postal code", max_length=12)
    city = forms.CharField(label="City", max_length=1024)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Re-enter password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        r = User.objects.filter(username=username)
        if r:
            raise ValidationError("Username already exists")
        return username

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise ValidationError("Passwords don't match")

        return password_confirm

    class Meta:
        model = Customer
        fields = ['f_name', 'l_name', 'email', 'phone']


class PaymentForm(forms.ModelForm):
    class Meta:
        model = PaymentInfo
        fields = ['name', 'card_num', 'exp_month', 'exp_year', 'cvv']


class VisitorForm(forms.ModelForm):
    class Meta:
        model = Visitor
        fields = ['f_name', 'l_name', 'phone']


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['f_name', 'l_name', 'phone']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'review_text']

orders/views.py
import urllib

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import redirect
# Create your views here.
from django.shortcuts import render

from .forms import *
from .models import Customer, Dish, Order, OrderItem, PaymentInfo, Address, Review
from .models import Restaurant
from django.forms.models import model_to_dict


# Homepage
def index(request):
    return render(request, 'orders/index.html', {})


def menu(request):
    context = {'items': Dish.objects.all()}
    print(Dish.objects.all())
    return render(request, 'orders/menu.html', context)


def main(request):
    context = {'r': Restaurant.objects.all()}
    print(Restaurant.objects.all())
    return render(request, 'orders/main.html', context)


def review(request, id):
    if request.method == 'POST':
        f = ReviewForm(request.POST)
        if f.is_valid():
            rev: Review = f.save(commit=False)
            customer = Customer.objects.get(user=request.user)
            rev.dish = Dish.objects.get(pk=id)
            rev.reviewer = request.user
            rev.save()
            messages.success(request, 'Review added')
            return render(request, 'orders/review.html', {'form': f})
    else:
        f = ReviewForm()
    return render(request, 'orders/review.html', {'form': f})


def orderPlaced(request):
    print(dict(request.POST))

    def get_dish(id):
        return Dish.objects.get(pk=id)

    customer = Customer.objects.get(user=request.user)

    orders = {get_dish(k): int(v[0]) for k, v in request.POST.items() if k != 'csrfmiddlewaretoken' and int(v[0]) != 0}

    ord = Order(vis=customer)
    ord.save()
    for k, v in orders.items():
        ord_item = OrderItem(dish=k, quantity=v, order=ord)
        ord_item.save()
    context = {'orders': orders}
    return render(request, 'orders/orderplaced.html', context)


# logout for both users (restaurants and regular customers)
def logout(request):
    logout(request)
    return redirect("login")

def cookView(request):
    items = OrderItem.objects.filter(is_cooked=False)
    d = {'items': items, 'messages': []}
    if request.method == 'POST':
        print(dict(request.POST))
        for x in request.POST:
            if x != 'csrfmiddlewaretoken':
                item = OrderItem.objects.get(pk=int(x))
                item.is_cooked = True
                item.save()
        d['messages'].append(f'{item.quantity} {item.dish} are cooked!')
    return render(request,'orders/cookpage.html',d)
# Customer side of things

# Register customer account
# def customerRegister(request):
#     form = CustomerSignUpForm(request.POST or None)
#     if form.is_valid():
#         user = form.save(commit=False)
#         username = form.cleaned_data['username']
#         password = form.cleaned_data['password']
#         user.is_customer = True
#         user.set_password(password)
#         user.save()
#         user = authenticate(username=username, password=password)
#         if user is not None:
#             if user.is_active:
#                 login(request, user)
#                 return redirect("ccreate")
#     return render(request, 'orders/signup.html', context={'form': form})

# Better registration form
def add_payment_form(request):
    customer = Customer.objects.get(user=request.user)
    if request.method == 'POST':
        f = PaymentForm(request.POST)
        if f.is_valid():
            a = f.save(commit=False)
            a.customer = customer
            a.save()
            messages.success(request, 'Saved payment info')
            return redirect('orders:addpayment')
    else:
        f = PaymentForm()
    return render(request, 'orders/addpayment.html', {'form': f})


def customerRegister(request):
    if request.method == 'POST':
        f = CustomerSignUpForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            return render(request, 'orders/register.html', {'form': f})
    else:
        f = CustomerSignUpForm()
    return render(request, 'orders/register.html', {'form': f})


def realCustomerRegister(request):
    if request.method == 'POST':
        f = CustomerRegistrationForm(request.POST)
        if f.is_valid():
            a = f.save(commit=False)
            addr = Address(
                street_addr=f.cleaned_data['address'],
                zip_code=f.cleaned_data['zip_code'],
                city=f.cleaned_data['city']
            )
            addr.save()
            b = User.objects.create_user(
                username=f.cleaned_data['username'],
                password=f.cleaned_data['password'],
                email=a.email
            )
            b.save()
            a.user = b
            a.address = addr
            a.save()
            messages.success(request, 'Account created successfully')
            return render(request, 'orders/cregister.html', {'form': f})
    else:
        f = CustomerRegistrationForm()
    return render(request, 'orders/cregister.html', {'form': f})


def to_table(items, start_col=0):
    arr = [model_to_dict(x) for x in items]
    headers = [x for x in arr[0]]
    rows = [x.values() for x in arr]
    return {'headers': headers, 'rows': rows}


# Let customers log in
def customerLogin(request):
    if request.method == "POST":
        username = request.post['username']
        password = request.post['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect("profile")
            else:
                return render(request, 'orders/login.html', {'error message': 'Invalid Username and Password'})
        else:
            return render(request, 'orders/login.html', {'error message': 'Invalid Username and Password'})
    return render(request, 'orders/login.html')


# view customer profiles based on ids
# turn user into customer
# build context dictionary { 'visitor' : visitor }
# return render( request, 'orders/profile.html', context)

def customerProfile(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    addr = urllib.parse.quote(str(customer.address))
    info = PaymentInfo.objects.filter(customer=customer)
    # context = {'v': customer, 'i': info, 'location': addr}
    orders = Order.objects.filter(vis=customer)
    context = {'v': customer, 'i': info, 'location': addr, 'orders': orders}
    print(context)
    # context = {'visitor': user}
    return render(request, 'orders/profile.html', context)


# create the customer profiles
def createCustomer(request):
    form = CustomerForm(request.POST or None)
    if form.is_valid():
        form.save()
        return render(request, 'orders/profile_form.html', context={'form': form, 'title': "Complete Profile"})


# update any details on customer profiles
def updateCustomer(request):
    form = CustomerForm(request.POST or None, instance=request.user.customer)
    if form.is_valid():
        form.save()
        return redirect('profile')
    return render(request, 'orders/profile_form.html', context={'form': form, 'title': "Update Profile"})

# need to finish checkout function

orders/templates/orders/addpayment.html
{% extends "orders/order_base.html" %}
{% block navbar %}
<a href="{% url 'orders:profile' %}">Profile</a>
{% endblock %}
{% block title %}
Add Payment - {{ block.super }}
{% endblock %}

{% block content %}

     <div class="login">

         {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
         {% endif %}

         <h1>Add Payment Method</h1>
         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Add Payment Info" /></td>
                </tr>
             </table>
         </form>
         <a href="{% url 'orders:profile'%}">Back to Profile</a>
     </div>

{% endblock %}

orders/templates/orders/cookpage.html
{% extends 'base.html' %}

{% block title %}Pending Orders{% endblock %}

{% block content %}
{% for x in messages %}
<p>{{x}}</p>
{% endfor %}
<form method="post">
    {% csrf_token %}
<table class="menu profile">
    <tr>
        <th>Item</th>
        <th>Quantity</th>
        <th>Mark as ready</th>
    </tr>
    {% for x in items %}
    <tr>
        <td>{{x.dish.name}}</td>
        <td>{{x.quantity}}</td>
        <td><input type="submit" name="{{x.pk}}" value="Cook"></td>
    </tr>
    {% endfor %}
</table>
</form>
{% endblock %}

orders/templates/orders/cregister.html
{% extends "orders/order_base.html" %}

{% block title %}
    Create Customer - {{ block.super }}
{% endblock %}

{% block content %}

     <div class="login">

         {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h1>Create account</h1>

         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" /></td>
                </tr>
             </table>
         </form>
     </div>

{% endblock %}

orders/templates/orders/menu.html
{% extends 'orders/order_base.html' %}
{% block title %}Menu{% endblock %}
{% block content %}
<h1>MENU</h1>
<form action="{% url 'orders:orderplaced' %}" method="post">
    {% csrf_token %}
    <table class="menu">
        <tr>
            <th>Dish Name</th>
            <th>Description</th>
            <th>Reviews</th>
            <th>Price</th>
            <th>Quantity</th>
        </tr>
        {% for d in items %}
        <tr>
            <td><a href="{% url 'orders:review' d.pk %}">{{ d.name }}</a></td>
            <td>{{ d.description }}</td>
            <td>{{ d.rating }}</td>
            <td>{{ d.price }}</td>
            <td><input type="number" value="0" min="0" max="100" name="{{ d.pk }}"/></td>
        </tr>
        {% endfor %}
    </table>
    <input type="submit" value="Checkout"/>
</form>
{% endblock %}

orders/templates/orders/order_base.html
{% extends 'base.html' %}
{% block navbar %}
<a href="{% url 'orders:profile' %}">Profile</a>
<a href="{% url 'orders:menu' %}">Menu</a>
{% endblock %}

orders/templates/orders/orderplaced.html
{% extends "orders/order_base.html" %}
{% block title %}Order Placed{% endblock %}
{% block content %}
<a href="{% url 'orders:profile' %}"></a>
    {% for key, value in orders.items %}
    <p>You ordered {{value}} of {{key.name}}</p>
    {% endfor %}
{% endblock %}

orders/templates/orders/profile.html
{% extends 'orders/order_base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
<h1>PROFILE</h1>
<table class="menu profile">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Address</th>
        <th>Email</th>
        <th>Phone</th>
        <th>BlackListStatus</th>
    </tr>
    <tr>
        <td>{{ v.f_name }}</td>
        <td>{{ v.l_name }}</td>
        <td>{{ v.address }}</td>
        <td>{{ v.email }}</td>
        <td>{{ v.phone }}</td>
        <td>{{ v.blacklisted }}</td>
    </tr>
</table>
<h1>PAYMENT INFO</h1>
<a href="{% url 'orders:addpayment'%}">Add Payment Info</a>
<table class="menu profile">
    <tr>
        <th>Card Name</th>
        <th>Card Number</th>
        <th>Exp. Month</th>
        <th>Exp. Year</th>
        <th>CVV</th>
    </tr>
    {% for i in i %}
        <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.card_num }}</td>
            <td>{{ i.exp_month }}</td>
            <td>{{ i.exp_year }}</td>
            <td>{{ i.cvv }}</td>
        </tr>
        {% endfor %}
</table>
<h1>ORDER HISTORY</h1>
<table class="menu profile">
    <tr>
        <th>Order Time</th>
        <th>Price</th>
        <th>Status</th>
    </tr>
    {% for x in orders %}
    <tr>
        <td>{{x.order_time}}</td>
        <td>{{x.price}}</td>
        <td>Cooking</td>
    </tr>
    {% endfor %}
</table>
<form action="{% url 'orders:addpayment' %}" method="get">
    <input type="submit" value="Add Card"
         name="Submit" id="frm1_submit" />
</form>

<iframe width="600" height="450" frameborder="0" style="border:0"
src="https://www.google.com/maps/embed/v1/directions?origin=City+Hall,New+York,NY
&destination={{ location }}
&key=AIzaSyCTPKfDZTXUbICmEu6si2IgJ_1abYiMa_g" allowfullscreen></iframe>

{% endblock %}

orders/templates/orders/register.html
{% extends "orders/order_base.html" %}

{% block title %}
    Create User - {{ block.super }}
{% endblock %}

{% block content %}

     <div class="login">

         {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
         {% endif %}

         <h1>Create Account</h1>

         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" /></td>
                </tr>
             </table>
         </form>
     </div>

{% endblock %}

orders/templates/orders/review.html
{% extends "orders/order_base.html" %}

{% block title %}
    Create Customer - {{ block.super }}
{% endblock %}

{% block content %}

     <div class="login">

         {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h1>Leave Review</h1>

         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Submit Review" /></td>
                </tr>
             </table>
         </form>
     </div>

{% endblock %}